version: '3'

services:
  api:
    image: node:18
    working_dir: /api
    network_mode: 'host'
    volumes:
      - ./packages/api:/api
      - ./data:/data
    command:
      bash -c "curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
      && pnpm install && pnpm run dev"

  app:
    image: node:18
    working_dir: /app
    network_mode: 'host'
    volumes:
      - ./packages/app:/app
    command:
      bash -c "curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
      && pnpm install && pnpm run dev"
